// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transport struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transport) Reset()         { *m = Transport{} }
func (m *Transport) String() string { return proto.CompactTextString(m) }
func (*Transport) ProtoMessage()    {}
func (*Transport) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_0f3a94cfdbf9d94f, []int{0}
}
func (m *Transport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transport.Unmarshal(m, b)
}
func (m *Transport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transport.Marshal(b, m, deterministic)
}
func (dst *Transport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transport.Merge(dst, src)
}
func (m *Transport) XXX_Size() int {
	return xxx_messageInfo_Transport.Size(m)
}
func (m *Transport) XXX_DiscardUnknown() {
	xxx_messageInfo_Transport.DiscardUnknown(m)
}

var xxx_messageInfo_Transport proto.InternalMessageInfo

func (m *Transport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transport) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DummyMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyMessage) Reset()         { *m = DummyMessage{} }
func (m *DummyMessage) String() string { return proto.CompactTextString(m) }
func (*DummyMessage) ProtoMessage()    {}
func (*DummyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_0f3a94cfdbf9d94f, []int{1}
}
func (m *DummyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyMessage.Unmarshal(m, b)
}
func (m *DummyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyMessage.Marshal(b, m, deterministic)
}
func (dst *DummyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyMessage.Merge(dst, src)
}
func (m *DummyMessage) XXX_Size() int {
	return xxx_messageInfo_DummyMessage.Size(m)
}
func (m *DummyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DummyMessage proto.InternalMessageInfo

func (m *DummyMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Transport)(nil), "event.Transport")
	proto.RegisterType((*DummyMessage)(nil), "event.DummyMessage")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_0f3a94cfdbf9d94f) }

var fileDescriptor_event_0f3a94cfdbf9d94f = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x4c, 0xb9, 0x38, 0x43,
	0x8a, 0x12, 0xf3, 0x8a, 0x0b, 0xf2, 0x8b, 0x4a, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73,
	0xf2, 0x13, 0x53, 0x24, 0x58, 0x14, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x25, 0x15, 0x2e, 0x1e,
	0x97, 0xd2, 0xdc, 0xdc, 0x4a, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x11, 0x2e, 0xd6,
	0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0xa8, 0x66, 0x08, 0x27, 0x89, 0x0d, 0x6c, 0x95, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xc0, 0xef, 0x52, 0x2f, 0x79, 0x00, 0x00, 0x00,
}
